Frozen esdt tokens
multiversx/mx-chain-es-indexer-go pull request #200
Opened 2023-01-17 12:53 UTC by miiu96

- Added an extra field `frozen` in the `tokens` index ( is true if an NFT is frozen)
- Extended the `accountsesdt` index

2023-01-19 11:31 UTC, iulianpascalau commented on process/elasticproc/logsevents/nftsPropertiesProcessor.go
> +		updateNFT = &data.NFTDataUpdate{Identifier: token, Pause: true}
could have been multiline. Also on L100

2023-01-19 11:54 UTC, miiu96 commented on integrationtests/testdata/accountsESDTWithTokenType/account-esdt.json
> +	"properties": "ok",
reverted the changed.

2023-01-19 11:58 UTC, miiu96 commented on process/elasticproc/accounts/accountsProcessor_test.go
> +	// Test with valid input that returns true
changed.

2023-01-19 12:00 UTC, miiu96 commented on process/elasticproc/converters/tokenMetaData.go
> +		freezeOrUnfreezeTokenIndex := (nftUpdate.Freeze || nftUpdate.UnFreeze) && !accountESDT
changed

2023-01-19 12:02 UTC, miiu96 commented on .github/workflows/pr-integration-tests.yml
> +    name: Elasticsearch v7.17.8
added

2023-01-19 12:03 UTC, miiu96 commented on integrationtests/logsCrossShard_test.go
>  	// INDEX ON SOURCE
changed

2023-01-19 12:03 UTC, miiu96 commented on process/elasticproc/accounts/accountsProcessor.go
> +	return value, accountTokenData.Properties, tokenMetaData, nil
The `encode-to-string` part is done at the node level.

2023-01-19 12:04 UTC, miiu96 commented on process/elasticproc/logsevents/nftsPropertiesProcessor.go
> +		updateNFT = &data.NFTDataUpdate{Identifier: token, Pause: true}
done

2023-01-19 13:27 UTC, bogdan-rosianu approved these changes

2023-01-20 09:30 UTC, iulianpascalau requested changes

2023-01-20 09:30 UTC, iulianpascalau commented on integrationtests/accountsESDTRollback_test.go
> +		Properties: []byte("3032"),
why not testing with `6f6b` **as the original test was**? 
In fact this is sent by the node as `hex("ok")`

2023-01-20 09:30 UTC, iulianpascalau commented on process/elasticproc/accounts/accountsProcessor_test.go
> +	require.Equal(t, "6f6b", prop)
inconsistent behavior: some tests get `3032` other `6f6b`

2023-01-20 09:57 UTC, iulianpascalau approved these changes

2023-01-20 13:35 UTC, merged